export const ROUTE_PERMISSIONS = {
  dashboard: null,
  students: "students.view",
  studentAdd: "students.create",
  studentUpdate: "students.update",
  studentDelete: "students.delete",
  attendance: "attendance.view",
  attendanceLive: "attendance.live",
  hostel: "hostel.view",
  hostelCreate: "hostel.create",
  hostelUpdate: "hostel.update",
  hostelDelete: "hostel.delete",
  hostelRooms: "hostel.rooms.view",   
  hostelRoomsCreate: "hostel.rooms.create",
  hostelRoomsUpdate: "hostel.rooms.update",
  hostelRoomsDelete: "hostel.rooms.delete",
  hostelAllocation: "hostel.allocations.view",
  hostelAllocationCreate: "hostel.allocations.create",
  hostelAllocationVacate: "hostel.allocations.vacate",
  hostelMaintenance: "hostel.maintenance.view",
  hostelNotices: "hostel.notices.view",
  reports: "reports.view",
  notifications: "notifications.view",
  settings: "settings.view",
  users: "users.view",
  userRoleAssign: "users.roles.assign",
  roles: "roles.view", 
  roleCreate: "roles.create",
  roleUpdate: "roles.update",
  roleDelete: "roles.delete",
  roleAssign: "roles.assign",
  permissions: "permissions.view",
  permissionManage: "permissions.manage",
  modules: "modules.view",
  moduleManage: "modules.manage",
  developer: "developer.view",
  
};
